### ISSUE TITLE
Please update for Android 10

### ISSUE THREAD

**Issue by andris155** [itz63c/TopNotch-NotchBarKiller#3]
I tested with Android 10 Pixel Experience and cause this bug if rotate screen and rotate back.
![Screenshot_20190922-142511](https://user-images.githubusercontent.com/8324198/65387353-e6bb6200-dd46-11e9-9301-bdae47acb490.png)

**Comment by itz63c** [comment]
I'll look into it soon

**Comment by andris155** [comment]
Latest PE ROM fixed this.
